# ClusterSecretStore para GCP Secret Manager
# Auth vía Service Account Key (no es GKE, no hay Workload Identity)
apiVersion: external-secrets.io/v1
kind: ClusterSecretStore
metadata:
  name: gcp-secret-manager
spec:
  provider:
    gcpsm:
      projectID: urbanqualityproject-dev
      auth:
        secretRef:
          secretAccessKeySecretRef:
            name: gcpsm-secret
            key: secret-access-credentials
            namespace: external-secrets
