# External Secrets Operator
# Sincroniza secretos desde GCP Secret Manager hacia Kubernetes
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: external-secrets
  namespace: argocd
spec:
  project: default
  sources:
    - repoURL: https://charts.external-secrets.io
      chart: external-secrets
      targetRevision: 1.2.0
      helm:
        valueFiles:
          - $values/values/dev/external-secrets.yaml
    - repoURL: git@github.com:jar-work/urban-k8s.git
      targetRevision: main
      ref: values
  destination:
    server: https://kubernetes.default.svc
    namespace: external-secrets
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
