# ClusterSecretStore y ExternalSecrets para todas las apps
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: external-secrets-config
  namespace: argocd
spec:
  project: default
  source:
    repoURL: git@github.com:jar-work/urban-k8s.git
    targetRevision: main
    path: manifests/external-secrets/dev
  destination:
    server: https://kubernetes.default.svc
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
